version: "3.4"

services:
  server:
    build: ./docker/webhook
    depends_on:
      - ngrok
    volumes:
      - "./logs:/logs"
      - "./config.yml:/config.yml:ro"
    env_file:
      - .env

  ngrok:
    image: wernight/ngrok
    environment:
      NGROK_AUTH: "${NGROK_AUTH}"
      NGROK_PORT: server:8080
      NGROK_PROTOCOL: "HTTPS"
      NGROK_REGION: "jp"
    restart: always
